import { NextResponse } from "next/server";
import { createAIProvider } from "@gamer-cv/services";

/**
 * GET /api/ai/status — reports which AI provider is active and whether it is a
 * real (network-calling) provider or the deterministic mock. Used by the UI to
 * show the user honestly whether their CV will be generated by a real model or
 * by the offline mock (§30 — never fake the AI). Does NOT expose any secret.
 */
export function GET() {
  let providerId = "mock";
  let real = false;
  let configured = true;
  let detail = "Mock (offline, déterministe).";
  try {
    const { providerId: id } = createAIProvider();
    providerId = id;
    real = id === "anthropic";
    if (id === "anthropic") {
      detail = "Anthropic (génération réelle par IA).";
    } else {
      detail = "Mock (offline, déterministe) — définis AI_PROVIDER=anthropic + ANTHROPIC_API_KEY pour une vraie génération.";
    }
  } catch (err) {
    configured = false;
    detail = err instanceof Error ? err.message : "Provider IA mal configuré.";
  }
  return NextResponse.json({ providerId, real, configured, detail });
}
